### ISSUE TITLE
Re-evaluate and expand default kernel options

### ISSUE THREAD

**Issue by AndrewFasano** [rehosting/linux_builder#24]
@lisi-w identified that our kernel options have changed in some meaningful ways from older kernels we were using. For example `NET_NS` used to be enabled and now it isn't.

We should 1) come up with a list of options that we've previously added / identify new options that seem likely to generally help (i.e., add features without breaking things) and 2) revise/refine our configs and infrastructure to integrate these.

Right now I'm not sure how to even generate a list of config options for a given kernel - we should probably document that and ensure it matches what we'd expect before/after tackling this issue.

**Comment by AndrewFasano** [comment]
Here's a good place where we've previously had kernel options set: https://github.com/panda-re/linux/blob/4.10_hc_dyndev/config.armel (and also the config.<other_arch> files). We should try to integrate these options with our current configs - we definitely lost some important values, for example (but not just):
```
CONFIG_NAMESPACES=y
CONFIG_UTS_NS=y
CONFIG_IPC_NS=y
CONFIG_PID_NS=y
CONFIG_NET_NS=y
```

**Comment by AndrewFasano** [comment]
@be32826 will give this a try - hoping to get this wrapped up by ~EOD

**Comment by AndrewFasano** [comment]
@be32826 fixed linting. Now we want to add some new kernel options - the ones above
```
CONFIG_BRIDGE_NF_EBTABLES=y
```

@coolkingcole has more options he wants

**Comment by coolkingcole** [comment]
I'm pretty sure that this error is due to needing segmentation support:
```
Cannot set device tcp segmentation offload settings: Operation not supported
```
## Options
```
CONFIG_NET_TSO
CONFIG_MII
```
These options are probably already on, but required for these options
```
CONFIG_INET
CONFIG_NETDEVICES
CONFIG_NET_IPV6
```

I was also looking at a linksys that was looking for this device: `/proc/net/psched`

I could fake that device, but It might be nicer to just have these enabled for real
```
CONFIG_NET_SCHED=y
CONFIG_NET_CLS_ACT=y
```

I haven't tested these, but they look like reasonable things to turn on for router kernels.

**Comment by be32826** [comment]
I added all these except `CONFIG_NET_TSO`, which doesn't seem to exist. It gives zero results when I search it on Google. It might have been a typo?

**Comment by coolkingcole** [comment]
Yes, sorry about that. Ignore that.
